require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  Exclude:
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'spec/**/*'

Style/StringLiterals:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
